// Auto-generated by scripts/generatePostsIndex.js - do not edit by hand
// Run: npm run generate-posts

const posts = [
  {
    "slug": "tiny-tone",
    "title": "Tiny Tone - My First Accepted Tiny-Tapeout Design",
    "description": "A small PWM-based audio tone generator submitted to TinyQV Tiny Tapeout — design notes and lessons learned.",
    "date": "2025-10-25",
    "url": "/blogs/tiny-tone"
  },
  {
    "slug": "riscv-linux",
    "title": "RISC-V: The Linux of Hardware",
    "description": "At Homebrew, we talk a lot about Linux and FOSS software. But what if I told you there’s a Linux moment happening in hardware too?",
    "date": "2025-09-07",
    "url": "/blogs/riscv-linux"
  },
  {
    "slug": "what-is-a-soc",
    "title": "What is a System-on-Chip, Really?",
    "description": "A gentle breakdown of what SoCs are and why I’m obsessed with them.",
    "date": "2025-07-18",
    "url": "/blogs/what-is-a-soc"
  },
  {
    "slug": "aetheron",
    "title": "Aetheron: Bringing My Own SoC to Life",
    "description": "From wires to life: how I built and booted my own System-On-Chip using BlueSpec SystemVerilog",
    "date": "2024-06-18",
    "url": "/blogs/aetheron"
  }
];

export default posts;
