// Auto-generated by scripts/generatePostsIndex.js - do not edit by hand
// Run: npm run generate-posts

const posts = [
  {
    "slug": "riscv-toolchain",
    "title": "You Don't Need Expensive Tools to Play with Silicon",
    "description": "A hands-on guide to free, open-source tools that let students design, simulate, and build real processors—no million-dollar lab required.",
    "date": "2026-02-07",
    "url": "/blogs/riscv-toolchain"
  },
  {
    "slug": "simt_warp_divergence",
    "title": "Why GPU Threads Aren’t What They Look Like: SIMT + Divergence Explained",
    "description": "An intermediate look at how GPU ‘threads’ really behave under the SIMT model, why warps share an instruction stream, and what actually happens when control flow splits.",
    "date": "2025-12-02",
    "url": "/blogs/simt_warp_divergence"
  },
  {
    "slug": "tiny-tone",
    "title": "Tiny Tone - My First Accepted Tiny-Tapeout Design",
    "description": "A small PWM-based audio tone generator submitted to TinyQV Tiny Tapeout — design notes and lessons learned.",
    "date": "2025-10-25",
    "url": "/blogs/tiny-tone"
  },
  {
    "slug": "riscv-linux",
    "title": "RISC-V: The Linux of Hardware",
    "description": "At Homebrew, we talk a lot about Linux and FOSS software. But what if I told you there’s a Linux moment happening in hardware too?",
    "date": "2025-09-07",
    "url": "/blogs/riscv-linux"
  },
  {
    "slug": "aetheron",
    "title": "Aetheron: Bringing My Own SoC to Life",
    "description": "From wires to life: how I built and booted my own System-On-Chip using BlueSpec SystemVerilog",
    "date": "2025-07-18",
    "url": "/blogs/aetheron"
  },
  {
    "slug": "what-is-a-soc",
    "title": "What is a System-on-Chip, Really?",
    "description": "A gentle breakdown of what SoCs are and why I’m obsessed with them.",
    "date": "2025-07-18",
    "url": "/blogs/what-is-a-soc"
  }
];

export default posts;
