// Auto-generated by scripts/generatePostsIndex.js - do not edit by hand
// Run: npm run generate-posts

const posts = [
  {
    "slug": "tiny-tone",
    "title": "Tiny Tone - My First Accepted Tiny-Tapeout Design",
    "description": "A small PWM-based audio tone generator submitted to TinyQV Tiny Tapeout — design notes and lessons learned.",
    "date": "2025-10-25",
    "url": "/blogs/tiny-tone"
  },
  {
    "slug": "aetheron",
    "title": "Aetheron: Bringing My Own SoC to Life",
    "description": "My journey building a RISC-V SoC from scratch designed in Bluespec.",
    "date": "2024-06-18",
    "url": "/blogs/aetheron"
  },
  {
    "slug": "resona",
    "title": "Resona: Rust, RISC-V Assembly, and DSP Kernels",
    "description": "A deep dive into building a tiny DSP-inspired simulator using Rust and hand-written RISC-V Assembly.",
    "date": "2024-04-05",
    "url": "/blogs/resona"
  },
  {
    "slug": "what-is-a-soc",
    "title": "What is a System-on-Chip, Really?",
    "description": "An accessible introduction to System-on-Chips — what they are and why they matter.",
    "date": "2023-12-01",
    "url": "/blogs/what-is-a-soc"
  }
];

export default posts;
