// Auto-generated by scripts/generateGalleryImages.js
// Do not edit by hand

const images = [
  {
    "original": "/assets/images/gallery/car_1.jpeg",
    "srcset": "/assets/images/gallery/generated/car_1-480w.jpeg 480w",
    "alt": "car 1"
  },
  {
    "original": "/assets/images/gallery/cat_1.jpeg",
    "srcset": "/assets/images/gallery/generated/cat_1-480w.jpeg 480w, /assets/images/gallery/generated/cat_1-1024w.jpeg 1024w",
    "alt": "cat 1"
  },
  {
    "original": "/assets/images/gallery/drawing_1.jpeg",
    "srcset": "/assets/images/gallery/generated/drawing_1-480w.jpeg 480w",
    "alt": "drawing 1"
  },
  {
    "original": "/assets/images/gallery/drawing_2.jpeg",
    "srcset": "/assets/images/gallery/generated/drawing_2-480w.jpeg 480w, /assets/images/gallery/generated/drawing_2-1024w.jpeg 1024w",
    "alt": "drawing 2"
  },
  {
    "original": "/assets/images/gallery/drawing_3.jpeg",
    "srcset": "/assets/images/gallery/generated/drawing_3-480w.jpeg 480w",
    "alt": "drawing 3"
  },
  {
    "original": "/assets/images/gallery/flower_1.jpeg",
    "srcset": "/assets/images/gallery/generated/flower_1-480w.jpeg 480w, /assets/images/gallery/generated/flower_1-1024w.jpeg 1024w",
    "alt": "flower 1"
  },
  {
    "original": "/assets/images/gallery/moon_1.jpeg",
    "srcset": "/assets/images/gallery/generated/moon_1-480w.jpeg 480w",
    "alt": "moon 1"
  },
  {
    "original": "/assets/images/gallery/sky_1.jpeg",
    "srcset": "/assets/images/gallery/generated/sky_1-480w.jpeg 480w",
    "alt": "sky 1"
  },
  {
    "original": "/assets/images/gallery/sky_2.jpeg",
    "srcset": "/assets/images/gallery/generated/sky_2-480w.jpeg 480w",
    "alt": "sky 2"
  },
  {
    "original": "/assets/images/gallery/sky_3.jpeg",
    "srcset": "/assets/images/gallery/generated/sky_3-480w.jpeg 480w",
    "alt": "sky 3"
  },
  {
    "original": "/assets/images/gallery/sky_4.jpeg",
    "srcset": "/assets/images/gallery/generated/sky_4-480w.jpeg 480w, /assets/images/gallery/generated/sky_4-1024w.jpeg 1024w",
    "alt": "sky 4"
  },
  {
    "original": "/assets/images/gallery/trees_1.jpeg",
    "srcset": "/assets/images/gallery/generated/trees_1-480w.jpeg 480w, /assets/images/gallery/generated/trees_1-1024w.jpeg 1024w",
    "alt": "trees 1"
  },
  {
    "original": "/assets/images/gallery/trees_2.jpeg",
    "srcset": "/assets/images/gallery/generated/trees_2-480w.jpeg 480w",
    "alt": "trees 2"
  },
  {
    "original": "/assets/images/gallery/trees_3.jpeg",
    "srcset": "/assets/images/gallery/generated/trees_3-480w.jpeg 480w",
    "alt": "trees 3"
  }
];

export default images;
